#!/bin/bash

CONTAINER_IP=$(cat /etc/hosts | grep 172 | cut -f 1 -d$'\t')
echo "Found IP of container: $CONTAINER_IP"

GFS_MOUNTPOINT="/gfs"
mkdir -p $GFS_MOUNTPOINT

ORIENTDB_HOST=${ORIENTDB_HOST:-10.88.88.183}
ORIENTDB_USER=${ORIENTDB_USER:-root}
ORIENTDB_PASSWORD=${ORIENTDB_PASSWORD:-root}
ORIENTDB_PORT=${ORIENTDB_PORT:-8182}

RABBITMQ_HOST=${RABBITMQ_HOST:-10.88.88.183}
RABBITMQ_USER=${RABBITMQ_USER:-rabbitmq}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-rabbitmq}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}

python \
    /gremlinfs/src/py/gremlinfs/gremlinfs.py \
    $GFS_MOUNTPOINT \
    $ORIENTDB_HOST \
    $ORIENTDB_PORT \
    $ORIENTDB_USER \
    $ORIENTDB_PASSWORD \
    $RABBITMQ_HOST \
    $RABBITMQ_PORT \
    $RABBITMQ_USER \
    $RABBITMQ_PASSWORD