version: '3'
services:

  theia:
    build:
      context: ./
      dockerfile: Dockerfile.theia
    volumes:
      - "./:/app"
    environment:
      GFS_FS_NAME: "gremlinfs1"
      GFS_FS_MOUNT: /home/project
      GREMLIN_HOST: "orientdb"
      GREMLIN_PORT: "8182"
      GREMLIN_USERNAME: "root"
      GREMLIN_PASSWORD: "root"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "rabbitmq"
      RABBITMQ_PASSWORD: "rabbitmq"
    privileged: true
    cap_add: 
      - SYS_ADMIN
      - MKNOD
    devices:
      - "/dev/fuse:/dev/fuse"
    restart: on-failure
    hostname: "theia"
    networks:
      - gremlinfs
    expose:
      - 3000
    ports:
      - 3000:3000
    # depends_on:
    #   - orientdb
    #   - rabbitmq
    # links:
    #   - orientdb
    #   - rabbitmq

networks:
  gremlinfs: 
    external:
      name: gremlinfs
