version: '3'
services:

  # docker pull neo4j
  neo4j:
    image: "neo4j:4.2"
    hostname: "neo4j"
    networks:
      - gremlinfs

  # https://hub.docker.com/r/tinkerpop/gremlin-server/
  gremlin:
    image: "tinkerpop/gremlin-server:3.4"
    hostname: "gremlin"
    networks:
      - gremlinfs

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_LOG_BASE: "/var/log/rabbitmq"
    hostname: "rabbitmq"
    networks:
      - gremlinfs
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

networks:
  gremlinfs: 
    external:
      name: gremlinfs
