FROM python:3.6.12-alpine3.11

RUN apk update && \
    apk add \
        py3-pip \
        py3-gobject3 \
        libblockdev-dev \
        py3-libblockdev \
        py3-rtslib \
        build-base \
        udev 

ADD . /gremlinfs
RUN pip3 install -r /gremlinfs/requirements.txt
# mount point
RUN mkdir /gfs
WORKDIR gremlinfs

CMD ["bash", "/gremlinfs/docker_start_gremlinfs.sh"]
